### ISSUE TITLE
TaskLists: Todo flavored GFM

### ISSUE THREAD

**Issue by LeaX-XIV** [LeaX-XIV/Logo#3]
- [x] Allow simple math operations as arguments
- [x] Allow procedure calls inside a `repeat` block
- [x] Enhance regex readability
- [ ] Add localization to interpreter
- [ ] Optimize algorithm for faster performance
- [ ] Add toggle auto-run
- [ ] Add save canvas as png
- [ ] Grasp trigonometric transformations for `clearscreen`, `clean` and `home` commands
- [ ] Rework UI
- [ ] \(Optional) Add more colors
- [ ] \(Optional) Add zoom
